version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  app:
    build: .
    